"""
Feature extraction script for MCQ Difficulty Estimation Pipeline

Reads the training data (training_data.json).
The training data is generated by the RAG pipeline 
Computes features from text for each MCQ and exports:
    - features.csv : tabular features 
    - tfidf_matrix : sparse TF-IDF matrix for question stems 
"""

import os 
import re 
import json 
import pickle 
from pathlib import Path 

import numpy as np 
import pandas as pd 
from tqdm import tqdm

import textstat 
import spacy
from sentence_transformers import SentenceTransformer 
from wordfreq import zipf_frequency
from sklearn.feature_extraction import TfidfVectorizer 


class MCQFeatureExtractor:
    """Extracts 24 features from an MCQ dictionary (question, options, correct_answer, retrieved_chunks)."""

    def __init__(self, all_questions=None):
        """
        Args:
            all_questions: optional list of MCQ dicts used to fit global TF‑IDF. If None, TF‑IDF will be fitted on the fly later.
        """
        self.sentence_encoder = None
        self.nlp = None
        self.tfidf_vectorizer = None
        self.tfidf_fitted = False

        # Load models
        self.sentence_encoder = SentenceTransformer('all-MiniLM-L6-v2')
        self.nlp = spacy.load("en_core_web_sm")

    @staticmethod
    def _readability_features(text):
        """Compute 6 readability scores."""
        if not text or len(text.strip()) < 3:
            return [0.0] * 6
        return [
            textstat.flesch_reading_ease(text),
            textstat.flesch_kincaid_grade(text),
            textstat.automated_readability_index(text),
            textstat.gunning_fog(text),
            textstat.coleman_liau_index(text),
            textstat.smog_index(text),
        ]

    @staticmethod
    def _linguistic_basic_features(question, options, correct_answer):
        """
        Returns:
            word_count_stem, sentence_count_stem, avg_word_len_stem,
            question_to_option_ratio, total_word_count_all
        """
        stem = question
        all_option_text = " ".join(options.values())
        correct_text = correct_answer

        # Word counts
        stem_words = stem.split()
        option_words = all_option_text.split()
        correct_words = correct_text.split()
        stem_word_count = len(stem_words)
        option_word_count = len(option_words)
        total_word_count = stem_word_count + option_word_count + len(correct_words)

        # Sentence counts
        stem_sentences = re.split(r'[.!?]+', stem)
        stem_sentence_count = len([s for s in stem_sentences if s.strip()])

        # Average word length in stem
        if stem_words:
            avg_word_len_stem = sum(len(w) for w in stem_words) / len(stem_words)
        else:
            avg_word_len_stem = 0.0

        # Question-to-Option length ratio
        avg_option_len = len(all_option_text) / len(options) if options else 1
        if avg_option_len > 0:
            q_to_o_ratio = len(stem) / avg_option_len
        else:
            q_to_o_ratio = 0.0

        return {
            "stem_word_count": stem_word_count,
            "stem_sentence_count": stem_sentence_count,
            "avg_word_len_stem": avg_word_len_stem,
            "question_to_option_ratio": q_to_o_ratio,
            "total_word_count": total_word_count,
        }

    def _embedding_similarity(self, correct_answer, options):
        """Compute average cosine similarity between correct and each distractor."""
        if self.sentence_encoder is None:
            return 0.0

        all_texts = [correct_answer] + list(options.values())
        try:
            embeddings = self.sentence_encoder.encode(all_texts, convert_to_tensor=True)
            correct_emb = embeddings[0]
            distractor_embs = embeddings[1:]

            if len(distractor_embs) == 0:
                return 0.0

            from torch.nn.functional import cosine_similarity
            sims = [cosine_similarity(correct_emb.unsqueeze(0), d.unsqueeze(0)).item() for d in distractor_embs]
            return float(np.mean(sims))
        except Exception:
            return 0.0

    def _syntactic_features(self, text):
        """
        Returns:
            parse_tree_depth, pos_ratio_noun, pos_ratio_verb, pos_ratio_adj, clause_count
        """
        if self.nlp is None or not text:
            return 0.0, 0.0, 0.0, 0.0, 0

        try:
            doc = self.nlp(text)
            if len(doc) == 0:
                return 0.0, 0.0, 0.0, 0.0, 0

            # POS ratios
            pos_counts = {"NOUN": 0, "VERB": 0, "ADJ": 0}
            for token in doc:
                if token.pos_ in pos_counts:
                    pos_counts[token.pos_] += 1
            total_pos = len(doc)
            pos_ratio_noun = pos_counts["NOUN"] / total_pos if total_pos else 0.0
            pos_ratio_verb = pos_counts["VERB"] / total_pos if total_pos else 0.0
            pos_ratio_adj = pos_counts["ADJ"] / total_pos if total_pos else 0.0

            # Parse tree depth (max depth from ROOT)
            def _max_depth(token, depth=0):
                if not list(token.children):
                    return depth
                return max(_max_depth(child, depth + 1) for child in token.children)

            root = [token for token in doc if token.dep_ == "ROOT"]
            if root:
                depth = _max_depth(root[0], 0)
            else:
                depth = 0

            # Clause count (rough heuristic: count of 'conj' + 'ccomp' + 'xcomp' + 'advcl')
            clause_deps = {"conj", "ccomp", "xcomp", "advcl"}
            clause_count = sum(1 for token in doc if token.dep_ in clause_deps)

            return float(depth), pos_ratio_noun, pos_ratio_verb, pos_ratio_adj, clause_count

        except Exception:
            return 0.0, 0.0, 0.0, 0.0, 0

    @staticmethod
    def _distractor_features(correct_answer, options):
        """
        Returns:
            distractor_count, avg_lexical_overlap, length_variance
        """
        distractors = list(options.values())
        d_count = len(distractors)

        if d_count == 0 or not correct_answer:
            return d_count, 0.0, 0.0

        # Lexical overlap (Jaccard) between correct and each distractor
        def jaccard(a, b):
            a_set, b_set = set(a.split()), set(b.split())
            if not a_set or not b_set:
                return 0.0
            return len(a_set & b_set) / len(a_set | b_set)

        overlaps = [jaccard(correct_answer, d) for d in distractors]
        avg_overlap = float(np.mean(overlaps)) if overlaps else 0.0

        # Length variance
        lengths = [len(d) for d in distractors]
        length_variance = float(np.var(lengths)) if lengths else 0.0

        return d_count, avg_overlap, length_variance

    @staticmethod
    def _lexical_sophistication(text, fallback_tfidf_score=None):
        """
        Returns average Zipf frequency (higher = more common).
        If wordfreq not available, uses fallback_tfidf_score (mean TF‑IDF).
        """
        if not text:
            return 0.0

        if HAS_WORDFREQ:
            words = text.split()
            freqs = []
            for w in words:
                try:
                    f = zipf_frequency(w, 'en')
                    freqs.append(f)
                except Exception:
                    freqs.append(0.0)
            return float(np.mean(freqs)) if freqs else 0.0
        else:
            # Use TF‑IDF mean as a proxy for sophistication
            return fallback_tfidf_score or 0.0

    @staticmethod
    def _complexity_markers(text):
        """Negation, modal/conditional, quantitative flags."""
        text_lower = text.lower()

        negation = bool(re.search(r'\b(not|no|never|neither|nor|none|without|except)\b', text_lower))
        modal_conditional = bool(re.search(r'\b(would|could|should|might|may|if|unless|provided|assuming|when|whereas)\b', text_lower))
        quantitative = bool(re.search(r'\b(\d+\.?\d*|calculate|compute|sum|difference|ratio|percent|quantitative|numeric)\b', text_lower))

        return int(negation), int(modal_conditional), int(quantitative)

    def _tfidf_mean(self, text, vectorizer):
        """Compute mean TF‑IDF score of tokens in text."""
        if not text or vectorizer is None:
            return 0.0
        try:
            vec = vectorizer.transform([text])
            # average non‑zero values
            non_zero = vec.data
            if len(non_zero) == 0:
                return 0.0
            return float(np.mean(non_zero))
        except Exception:
            return 0.0

    def extract_features(self, mcq, tfidf_vectorizer=None):
        """
        Extract all features from a single MCQ dict.

        Returns:
            dict: feature_name -> value (scalar or list for TF‑IDF)
        """
        question = mcq.get("question", "")
        options = mcq.get("options", {})
        correct_answer = mcq.get("correct_answer", "")
        retrieved_chunks = mcq.get("retrieved_chunks", [])
        if not retrieved_chunks:
            retrieved_chunks = []

        # Readability (stem + options combined)
        combined_text = question + " " + " ".join(options.values())
        readability = self._readability_features(combined_text)

        # Linguistic basics
        ling = self._linguistic_basic_features(question, options, correct_answer)

        # TF‑IDF mean (requires vectorizer)
        tfidf_mean = self._tfidf_mean(question, tfidf_vectorizer)

        # Embedding similarity
        emb_sim = self._embedding_similarity(correct_answer, options)

        # Syntactic (stem only)
        depth, noun_ratio, verb_ratio, adj_ratio, clause_count = self._syntactic_features(question)

        # Distractor features
        d_count, d_overlap, d_var = self._distractor_features(correct_answer, options)

        # Lexical sophistication
        lex_soph = self._lexical_sophistication(question, fallback_tfidf_score=tfidf_mean)

        # Complexity markers
        neg, modal, quant = self._complexity_markers(question)

        # Domain/Topic (fallback to PDF path or "unknown")
        domain = mcq.get("pdf_path", "unknown")
        if domain:
            domain = Path(domain).stem[:30]  # truncate


        return {
            # Readability
            "flesch_reading_ease": readability[0],
            "flesch_kincaid_grade": readability[1],
            "automated_readability_index": readability[2],
            "gunning_fog": readability[3],
            "coleman_liau": readability[4],
            "smog": readability[5],

            # Linguistic
            "stem_word_count": ling["stem_word_count"],
            "stem_sentence_count": ling["stem_sentence_count"],
            "avg_word_len_stem": ling["avg_word_len_stem"],
            "question_to_option_ratio": ling["question_to_option_ratio"],
            "total_word_count": ling["total_word_count"],

            # IR
            "tfidf_mean": tfidf_mean,

            # Semantic
            "embedding_similarity": emb_sim,

            # Syntactic
            "parse_tree_depth": depth,
            "pos_noun_ratio": noun_ratio,
            "pos_verb_ratio": verb_ratio,
            "pos_adj_ratio": adj_ratio,
            "clause_count": clause_count,

            # Distractor
            "distractor_count": d_count,
            "distractor_lexical_overlap": d_overlap,
            "distractor_length_variance": d_var,

            # Sophistication
            "lexical_sophistication": lex_soph,
            # Complexity markers
            "negation_present": neg,
            "modal_conditional_present": modal,
            "quantitative_present": quant,

            # Metadata
            "domain": domain,
            "difficulty_label": mcq.get("difficulty", ""),
        }


def main():
    """Main entry point."""
    
    INPUT_JSON = Path("training_data.json") 
    OUTPUT_CSV = Path("features.csv")
    OUTPUT_TFIDF = Path("tfidf_matrix.npz")
    OUTPUT_METADATA = Path("metadata.pkl")

    if not INPUT_JSON.exists():
        raise FileNotFoundError(f"Input JSON not found: {INPUT_JSON}")

    with open(INPUT_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    questions = data.get("questions", [])
    if not questions:
        raise ValueError("No 'questions' key found in the JSON.")

    print(f"Loaded {len(questions)} MCQs from {INPUT_JSON}")

    tfidf_vectorizer = None
    if HAS_SKLEARN:
        stems = [q.get("question", "") for q in questions]
        if any(stems):
            tfidf_vectorizer = TfidfVectorizer(max_features=1000, stop_words="english")
            tfidf_vectorizer.fit(stems)
            print(f"TF‑IDF fitted with vocabulary size: {len(tfidf_vectorizer.vocabulary_)}")
            tfidf_matrix = tfidf_vectorizer.transform(stems)
            from scipy.sparse import save_npz
            save_npz(OUTPUT_TFIDF, tfidf_matrix)
            print(f"Raw TF‑IDF matrix saved to {OUTPUT_TFIDF}")
    else:
        print("scikit‑learn not installed. TF‑IDF mean will be 0.")

    extractor = MCQFeatureExtractor()

    all_features = []
    for idx, mcq in enumerate(tqdm(questions, desc="Extracting features")):
        feat = extractor.extract_features(mcq, tfidf_vectorizer)
        feat["mcq_id"] = idx
        all_features.append(feat)

    df = pd.DataFrame(all_features)
    df.to_csv(OUTPUT_CSV, index=False)
    print(f"Features saved to {OUTPUT_CSV}")

    with open(OUTPUT_METADATA, "wb") as f:
        pickle.dump({"mcq_ids": list(range(len(questions)))}, f)
    print(f"Metadata saved to {OUTPUT_METADATA}")

    print("\n--- Feature preview (first 5 rows) ---")
    print(df.head())

    # ----- Summary statistics -----
    print("\n--- Summary statistics ---")
    print(df.describe())


if __name__ == "__main__":
    main()
